import { AuthProvider } from '../context/AuthContext';
import './styles.css';

export const metadata = {
  title: 'Cine Mundo',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="pt-br">
      <body>
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  )
}
